---
title: Gales
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```
# UK Gales Index

The data used in this plot is taken from https://crudata.uea.ac.uk/cru/data/lwt/ and shows the number of storms across the UK at three different levels of severity during the extended winter season (October to April).

```{r, echo=FALSE, out.width="100%",warning=FALSE,message=FALSE}
library(dplyr)
library(tidyr)
library(dygraphs)

dat <- read.csv("https://crudata.uea.ac.uk/cru/data/lwt/webdocs/gale_index_1200hrs_UK.csv")

## Select only severe gales and worse
gales <- dat %>%
    filter(!Gale.Index.exceedances=="gales",Month%in%c(11,12,1:4)) %>%
    mutate(year2=if_else(Month%in%c(11,12),Year+1,Year)) %>%
    group_by(year2) %>%
    summarise(Frequency=n())


gales <- dat %>%
    filter(Month%in%c(11,12,1:4)) %>%
    mutate(year2=if_else(Month%in%c(11,12),Year+1,Year)) %>%
    group_by(year2,Gale.Index.exceedances) %>%
    summarise(Frequency=n()) %>%
    spread(Gale.Index.exceedances,Frequency) %>%
    mutate_at(vars(-group_cols()), function(x)if_else(is.na(x),0,x)) %>%
    rename(severe.gales=`severe gales`,v.severe.gales=`very severe gales`)


dygraph(gales) %>%
    dySeries("v.severe.gales",label="Very Severe Gales") %>%
    dySeries("severe.gales",label="Severe Gales") %>%
    dySeries("gales",label="Gales") %>%
    dyOptions(stackedGraph = TRUE) %>%
    dyRangeSelector()

```